ingress:
  enabled: true
  host: rozert-pay-api.dev.betmaster.co

  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: >-
      88.196.79.147,148.251.194.118,144.76.89.116,5.9.56.146,77.83.247.25,185.103.110.148,92.223.79.196,5.253.43.186,95.174.68.163,176.97.66.82,38.180.106.228,79.133.109.6,178.132.2.201,38.180.179.187,62.112.11.40,178.63.186.236,142.132.147.100,157.90.89.246

jobs:
  sync:
    enabled: false
