repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        files: ^rozert-pay/
      - id: end-of-file-fixer
        files: ^rozert-pay/
      - id: check-yaml
        files: ^rozert-pay/
      - id: check-json
        files: ^rozert-pay/

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11
        files: ^rozert-pay/

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ "--profile", "black" ]
        files: ^rozert-pay/

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - "--ignore=E501,W503,F811"
          - "--exclude=rozert_pay/migrations"
        files: ^rozert-pay/
        additional_dependencies: [flake8-print]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.23.0
    hooks:
      - id: eslint
        args: ['--fix', '--ext', '.js,.jsx,.ts,.tsx', 'rozert-pay/front/src']
        files: ^rozert-pay/front/
        additional_dependencies:
          - eslint@^8.0.0
          - eslint-plugin-no-console-log
          - eslint-plugin-react
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - eslint-plugin-react-hooks

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.2
    hooks:
      - id: prettier
        args: ['--write', 'rozert-pay/front/src/']
        files: ^rozert-pay/front/src/
        exclude: ^rozert-pay/front/node_modules/
